# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculater02.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 330)
        MainWindow.setMinimumSize(QtCore.QSize(300, 330))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 291, 61))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 81, 320, 231))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.b7 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b7.setFont(font)
        self.b7.setObjectName("b7")
        self.gridLayout.addWidget(self.b7, 0, 0, 1, 1)
        self.b2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 2, 1, 1, 1)
        self.b_div = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b_div.setFont(font)
        self.b_div.setObjectName("b_div")
        self.gridLayout.addWidget(self.b_div, 0, 3, 1, 1)
        self.b5 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.gridLayout.addWidget(self.b5, 1, 1, 1, 1)
        self.b3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.gridLayout.addWidget(self.b3, 2, 2, 1, 1)
        self.b1 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 2, 0, 1, 1)
        self.b6 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.gridLayout.addWidget(self.b6, 1, 2, 1, 1)
        self.b_minus = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b_minus.setFont(font)
        self.b_minus.setObjectName("b_minus")
        self.gridLayout.addWidget(self.b_minus, 2, 3, 1, 1)
        self.b_clear = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b_clear.setFont(font)
        self.b_clear.setObjectName("b_clear")
        self.gridLayout.addWidget(self.b_clear, 3, 2, 1, 1)
        self.b9 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b9.setFont(font)
        self.b9.setObjectName("b9")
        self.gridLayout.addWidget(self.b9, 0, 2, 1, 1)
        self.b_plus = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b_plus.setFont(font)
        self.b_plus.setObjectName("b_plus")
        self.gridLayout.addWidget(self.b_plus, 3, 3, 1, 1)
        self.b4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.gridLayout.addWidget(self.b4, 1, 0, 1, 1)
        self.b0 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b0.setFont(font)
        self.b0.setObjectName("b0")
        self.gridLayout.addWidget(self.b0, 3, 0, 1, 1)
        self.b_point = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b_point.setFont(font)
        self.b_point.setObjectName("b_point")
        self.gridLayout.addWidget(self.b_point, 3, 1, 1, 1)
        self.b8 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b8.setFont(font)
        self.b8.setObjectName("b8")
        self.gridLayout.addWidget(self.b8, 0, 1, 1, 1)
        self.b_multi = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b_multi.setFont(font)
        self.b_multi.setObjectName("b_multi")
        self.gridLayout.addWidget(self.b_multi, 1, 3, 1, 1)
        self.b_right = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b_right.setFont(font)
        self.b_right.setObjectName("b_right")
        self.gridLayout.addWidget(self.b_right, 4, 3, 1, 1)
        self.b_left = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b_left.setFont(font)
        self.b_left.setObjectName("b_left")
        self.gridLayout.addWidget(self.b_left, 4, 2, 1, 1)
        self.b_equal = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.b_equal.setFont(font)
        self.b_equal.setObjectName("b_equal")
        self.gridLayout.addWidget(self.b_equal, 4, 0, 1, 2)
      #  MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "计算器"))
        MainWindow.setToolTip(_translate("MainWindow", "计算器"))
        MainWindow.setWhatsThis(_translate("MainWindow", "计算器"))
        self.b7.setText(_translate("MainWindow", "7"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.b_div.setText(_translate("MainWindow", "/"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b_minus.setText(_translate("MainWindow", "-"))
        self.b_clear.setText(_translate("MainWindow", "c"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b_plus.setText(_translate("MainWindow", "+"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.b_point.setText(_translate("MainWindow", "."))
        self.b8.setText(_translate("MainWindow", "8"))
        self.b_multi.setText(_translate("MainWindow", "*"))
        self.b_right.setText(_translate("MainWindow", ")"))
        self.b_left.setText(_translate("MainWindow", "("))
        self.b_equal.setText(_translate("MainWindow", "="))


if __name__=="__main__":
    import sys
    app=QtWidgets.QApplication(sys.argv)
    widget=QtWidgets.QWidget()
    ui=Ui_MainWindow()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
